[server]
headless = true
address = "127.0.0.1"
port = 8501
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#D42B2B"
backgroundColor = "#F5F6FA"
secondaryBackgroundColor = "#ffffff"
textColor = "#1C2333"
font = "sans serif"
